name: planet
description: "A new Flutter project."

# Empêche la publication accidentelle du package sur pub.dev.
publish_to: 'none'

# La version de l'application (nom + numéro de build)
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # Vous pouvez ajuster la version SDK en fonction de vos besoins (assurez-vous que c'est compatible avec votre version Flutter)

# Dépendances nécessaires au fonctionnement de l'application
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 # La dépendance `http` ne doit pas être imbriquée sous `flutter`
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Ajustement possible selon votre version de Flutter

# Section Flutter pour la configuration des assets et fonts
flutter:
  uses-material-design: true

  # Ajouter des images et autres fichiers d'assets ici si nécessaire
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Pour ajouter des polices personnalisées à votre application, ajoutez une section de polices ici
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
